# KD-Tree

In [ ]:
from scipy import spatial
import numpy as np

In [ ]:
spatial.KDTree

In [ ]:
x, y = np.mgrid[0:5, 2:8]

In [ ]:
x

In [ ]:
y

In [ ]:
print(zip(x.ravel(), y.ravel()))

In [ ]:
x.ravel()

In [ ]:
np.sqrt(np.square(0.1) + np.square(0.1) )

In [ ]:
tree = spatial.KDTree(list(zip(x.ravel(), y.ravel())))
pts = np.array([[0, 0], [2.1, 2.9]])
tree.query(pts)

# Calculating Euclidian Distance

### reading csv from one hot encoded csv dataset

In [ ]:
import pandas as pd
from scipy.spatial.distance import pdist, squareform

test_df = pd.read_csv("../herbarium-berlin-oneh.csv.gz",compression='gzip', encoding='utf-8', sep='|')

In [ ]:
dist = pdist(test_df, 'euclidean')
# dist_df = pd.DataFrame(squareform(dist))

In [ ]:
from sklearn.neighbors import DistanceMetric

dist = DistanceMetric.get_metric('euclidean')

X = [[0, 1, 2],[3, 4, 5]]
dist.pairwise(X)

In [ ]:
test_df.values

In [ ]:
dist.pairwise(test_df.values)

### reading csv from clean csv dataset

In [1]:
import pandas as pd

item_df_dr_0 = pd.read_csv("../herbarium-berlin-clean.csv", sep = '\t', index_col=False)
item_df_dr_0 = item_df_dr_0.drop(item_df_dr_0.columns[0], axis=1)

cal_btc_df = item_df_dr_0[["kingdom","phylum","class","order","family","genus","species","decimalLatitude","decimalLongitude"]]
oneh_cal_btc_df = pd.get_dummies(cal_btc_df,prefix=['kingdom','phylum','class','order','family','genus','species'])
oneh_cal_btc_df

/root/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/root/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

,decimalLatitude,decimalLongitude,kingdom_Chromista,kingdom_Fungi,kingdom_Plantae,phylum_Ascomycota,phylum_Bryophyta,phylum_Charophyta,phylum_Chlorophyta,phylum_Marchantiophyta,...,species_Ziziphus lotus,species_Ziziphus mauritiana,species_Ziziphus spina-christi,species_Zornia contorta,species_Zosima absinthifolia,species_Zoysia matrella,species_Zuvanda meyeri,species_Zygophyllum fabago,species_Zygophyllum macropterum,species_Zygophyllum pterocarpum
0,43.000278,16.003611,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,43.000557,-3.003333,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,36.009998,15.007500,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,43.000557,-6.000278,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,36.009998,15.007222,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,43.000557,-3.003333,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,43.000557,-6.002222,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,-16.912500,-70.908058,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,51.425835,13.265833,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,52.406944,14.554723,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,52.551945,12.679723,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,52.294445,14.049723,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,35.325001,23.916666,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,35.450001,27.186110,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,35.450001,27.186110,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,52.340553,12.935833,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,52.088058,12.925280,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,52.802776,13.563611,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,40.080280,21.298889,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,39.022499,21.878330,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,38.989719,21.842220,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,38.989719,21.842220,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,39.946671,21.567780,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,39.672218,21.818060,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,39.170280,21.896669,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,38.978062,21.911671,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,38.894718,21.881109,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,38.910278,21.921671,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,52.088612,12.903889,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,33.411945,-5.218056,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184951,39.333332,46.383335,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184952,35.883892,27.218056,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184953,37.033333,25.191666,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184954,40.833332,21.958334,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184955,34.917778,24.916945,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184956,40.595833,23.111111,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184957,35.067776,25.850555,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184958,37.636669,101.338333,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184959,38.641670,22.308332,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184960,42.650280,44.574165,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184961,37.126663,25.565832,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184962,37.516666,23.725000,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184963,35.401390,23.651112,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184964,36.933613,32.155834,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184965,39.640282,21.003059,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184966,41.158337,23.674999,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184967,35.291668,24.033333,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184968,40.983334,23.233334,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184969,37.233334,31.333334,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184970,41.750000,23.389999,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184971,42.659168,44.578888,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184972,40.425003,21.866667,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184973,41.108334,26.000000,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184974,37.087219,22.230833,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184975,42.658058,44.569443,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184976,37.049999,28.799999,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184977,50.349998,87.050003,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184978,53.542778,-10.137222,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184979,-11.500000,-41.983330,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184980,37.718891,20.730001,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
item_df_dr_0

In [ ]:
oneh_cal_btc_df.shape

In [ ]:
from sklearn.neighbors import DistanceMetric

dist = DistanceMetric.get_metric('euclidean')
dist.pairwise(oneh_cal_btc_df.values)

In [ ]:
from sklearn.metrics.pairwise import euclidean_distances
from scipy import sparse

sparse_df = oneh_cal_btc_df.to_sparse(fill_value=0)
X = sparse.csr_matrix(sparse_df.to_coo())

res = euclidean_distances(X, X)

In [ ]:
import numpy as np

X = oneh_cal_btc_df.to_sparse(fill_value=0)

In [ ]:
X.density

In [ ]:
X

In [ ]:
sparse_df

### Bießmann's method

In [2]:
from sklearn.metrics.pairwise import euclidean_distances
from scipy import sparse

sparse_df = oneh_cal_btc_df.to_sparse(fill_value=0)
X = sparse.csr_matrix(sparse_df.to_co())

In [6]:
type(X)

scipy.sparse.csr.csr_matrix

In [7]:
X.shape

(184981, 13834)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler(with_mean=False)
X_norm = scaler.fit_transform(X.T)

In [ ]:
X_norm

In [ ]:
similarities = X_norm.T.dot(X_norm)

In [ ]:
neighbors = similarities.argsort(axis=1)[:,-10:-1]

In [9]:
X[0]

<1x13834 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [12]:
X.dot(X[0,:].T).toarray().flatten().argsort()[1:5]

array([121810, 121818,  39900,    833])

In [16]:
from sklearn.preprocessing import StandardScaler

def sparse_similarity(X,top_k=5):
        
    scaler = StandardScaler(with_mean=False)
    X_norm = scaler.fit_transform(X.T).T

    return [X_norm.dot(X_norm[i,:].T).toarray().flatten().argsort()[1:top_k] for i in range(X.shape[0])]

In [ ]:
smlrt = sparse_similarity(X)

### calculating only on the taxonomy

In [ ]:
tax_oneh_cal_btc_df = oneh_cal_btc_df.drop(columns=['decimalLatitude', 'decimalLongitude'])
tax_oneh_cal_btc_df

In [ ]:
sparse_df = tax_oneh_cal_btc_df.to_sparse(fill_value=0)
X = sparse.csr_matrix(sparse_df.to_coo())

scaler = StandardScaler(with_mean=False)
X_norm = scaler.fit_transform(X.T)

In [ ]:
similarities = X_norm.T.dot(X_norm)

In [ ]:
X_norm

### chunk calculating euclidean distance

In [2]:
from numpy import linalg as LA
import numpy as np

In [ ]:
test_df = oneh_cal_btc_df.iloc[:10]

test_df

In [3]:
def calculate_ed(val_array, main_df):
    sim_res = np.array([])
    
    for index, row in main_df.iterrows():
        dis = LA.norm(row.values - val_array)
        sim_res = np.append(sim_res, dis)
    
    return np.argsort(sim_res)[:20]

In [ ]:
similar_item_array = []
used_df = oneh_cal_btc_df

for index, row in used_df.iterrows():
    #print("row : " + str(index), end='\r')
    res = calculate_ed(row.values, used_df)
    similar_item_array.append(res)
    
    
end_result = np.array(similar_item_array)
df1 = pd.DataFrame(end_result)
df1.to_csv("../result-similarity.csv", encoding='utf-8', header=False, index=False)

In [ ]:
end_result.shape

In [ ]:
df1 = pd.DataFrame(end_result)
df1.to_csv("../test-similarity.csv", encoding='utf-8', header=False, index=False)